framework:
    messenger:
        transports:
            outbox_events: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            App\Message\OutboxEvent: outbox_events

when@test:
    framework:
        messenger:
