framework:
    messenger:
        transports:
            outbox_events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\OutboxEventSerializer

        routing:
            App\Message\OutboxEvent: outbox_events

when@test:
    framework:
        messenger:
            transports:
                outbox_events:
                    dsn: 'in-memory://'
                    serializer: App\Messenger\OutboxEventSerializer
