
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-walleting}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-walleting}
      POSTGRES_USER: ${POSTGRES_USER:-walleting}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-walleting}", "-U", "${POSTGRES_USER:-walleting}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
