services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\Walleting\Outbox\OutboxMessageHandlerInterface:
            tags: ['app.outbox_message_handler']

    App\Walleting\Service\PostingExecutorInterface: '@App\Walleting\Service\PostingDbalExecutor'
    App\Walleting\Service\PostingTelemetryInterface: '@App\Walleting\Service\DatabasePostingTelemetry'
    App\Walleting\Service\PostingSloTransitionNotifierInterface: '@App\Walleting\Service\LoggingPostingSloTransitionNotifier'

    App\Walleting\:
        resource: '../src/'
        exclude: ['../src/Entity/', '../src/DependencyInjection/', '../src/WalletingBundle.php', '../src/Kernel.php']
