services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\Walleting\Handler\Outbox\WalletOutboxMessageHandlerInterface:
            tags: ['app.outbox_message_handler']

    App\Walleting\Service\WalletPostingExecutorInterface: '@App\Walleting\Service\WalletPostingDbalExecutor'
    App\Walleting\Service\WalletPostingTelemetryInterface: '@App\Walleting\Service\WalletDatabasePostingTelemetry'
    App\Walleting\Service\WalletPostingSloTransitionNotifierInterface: '@App\Walleting\Service\WalletLoggingPostingSloTransitionNotifier'

    App\Walleting\:
        resource: '../src/'
        exclude: ['../src/Entity/', '../src/DependencyInjection/', '../src/WalletingBundle.php', '../src/Kernel.php']
