services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\Outbox\OutboxMessageHandlerInterface:
            tags: ['app.outbox_message_handler']

    App\Service\PostingExecutorInterface: '@App\Service\PostingDbalExecutor'

    App\:
        resource: '../src/'
        exclude: ['../src/Entity/', '../src/Kernel.php']
